name: Feature Request
description: Submit a feature request
title: "feature request: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Before** submitting a feature request, make sure to search [existing issues](https://github.com/stevearc/oil.nvim/issues)
  - type: checkboxes
    attributes:
      label: Did you check docs and existing issues?
      description: Make sure you checked all of the below before submitting an issue
      options:
        - label: I have read all the docs
          required: true
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the feature you want
      description: A clear and concise description of what feature you want. Is there anything similar currently implemented?
    validations:
      required: true

